version: '3.7'

x-common: &common
    network_mode: host
    volumes:
        - ${VOLUME_DIRECTORY}:/home/me/volume
    environment:
        - COLUMNS
        - LINES
        - EDITOR

services:
    base:
        build: ./base
        image: base
        <<: *common
    burp:
        build: ./burp
        image: burp
        <<: *common
        environment:
            - DISPLAY
        volumes:
            - /home/$SUDO_USER/.Xauthority:/root/.Xauthority:ro
    ext:
        build: ./ext
        image: ext
        <<: *common
    int:
        build: ./int
        image: int
        cap_add:
            - NET_ADMIN
        <<: *common
    mob:
        build: ./mob
        image: mob
        <<: *common
        volumes:
            - ${VOLUME_DIRECTORY}:/home/me/volume
            - /dev/bus/usb:/dev/bus/usb
    web:
        build: ./web
        image: web
        <<: *common
    wifi:
        build: ./wifi
        image: wifi
        cap_add:
            - NET_ADMIN
        <<: *common
