version: '3.7'

x-common: &common
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
        - ${VOLUME_DIRECTORY}:/home/me/volume
    environment:
        - COLUMNS
        - LINES

services:
    base:
        build: ./base
        image: base
        <<: *common
    int:
        build: ./int
        image: int
        privileged: true
        <<: *common
    mob:
        build: ./mob
        image: mob
        privileged: true
        <<: *common
        volumes:
            - ${VOLUME_DIRECTORY}:/home/me/volume
            - /dev/bus/usb:/dev/bus/usb
    web:
        build: ./web
        image: web
        <<: *common
    wifi:
        build: ./wifi
        image: wifi
        privileged: true
        <<: *common
