version: '3.7'

x-common: &common
    network_mode: host
    volumes:
        - ${VOLUME_DIRECTORY}:/volume
        - /etc/localtime:/etc/localtime:ro
    environment:
        - COLUMNS
        - LINES
        - EDITOR
        - HOSTNAME

# If you ever connect to a local network whose IP address range overlaps with
# the default docker0 bridge configuration (172.17.0.0/16), you should change
# your /etc/docker/daemon.json file to instruct the use of another range like:
# {
#   "bip": "192.168.145.1/24"
# }
# The following lines will make compose use that configuration for profiles in
# bridge mode (network_mode: bridge):
networks:
    default:
        ipam:
            driver: default

# cpw assumes service names are used as image names
# configuring otherwise here will break cpw
services:
    base:
        build: ./base
        image: base
        <<: *common
    burp:
        build: ./burp
        image: burp
        <<: *common
        environment:
            - DISPLAY
            - HOSTNAME
            - _JAVA_AWT_WM_NONREPARENTING=1
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ${XAUTHORITY}:/root/.Xauthority:ro
            - ${VOLUME_DIRECTORY}:/volume
    ext:
        build: ./ext
        image: ext
        <<: *common
    int:
        build: ./int
        image: int
        cap_add:
            - NET_ADMIN
        <<: *common
    mob:
        build: ./mob
        image: mob
        <<: *common
        volumes:
            - ${VOLUME_DIRECTORY}:/volume
            - /dev/bus/usb:/dev/bus/usb
    web:
        build: ./web
        image: web
        <<: *common
    wifi:
        build: ./wifi
        image: wifi
        cap_add:
            - NET_ADMIN
        <<: *common
