FROM base

RUN pacman -Syu --noconfirm && \
    pacman -S \
        arjun \
        dirb \
        ffuf \
        nikto \
        nmap \
        nuclei \
        nuclei-templates \
        sqlmap \
        testssl.sh \
        wafw00f \
    --noconfirm --needed
