FROM base

RUN pacman -Syu --noconfirm && \
    pacman -S \
        arjun \
        dirb \
        blackarch/ffuf \
        nikto \
        nmap \
        sqlmap \
        testssl.sh \
        wafw00f \
    --noconfirm --needed
